import { Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import FormContextProvider from "@/context/FormContext";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Café de Altura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outfit.className} antialiased`}>
      <body className="">
        <FormContextProvider>
          <NavBar />
          {children}
        </FormContextProvider>
      </body>
    </html>
  );
}
